import { FilterType } from './types';
import { LayoutDashboard, Calendar, Clock, Pin, CheckCircle } from 'lucide-react';

export const NAVIGATION_ITEMS: { id: FilterType; icon: any }[] = [
  { id: 'all', icon: LayoutDashboard },
  { id: 'today', icon: Clock },
  { id: 'upcoming', icon: Calendar },
  { id: 'pinned', icon: Pin },
  { id: 'completed', icon: CheckCircle },
];

export const DEFAULT_NOTIFICATION_SOUND = 'https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3';

export const TRANSLATIONS = {
  uz: {
    all: 'Barcha vazifalar',
    today: 'Bugun',
    upcoming: 'Kelgusi',
    pinned: 'Muhim',
    completed: 'Bajarilgan',
    settings: 'Sozlamalar',
    search: 'Qidirish...',
    goodMorning: 'Xayrli tong',
    goodAfternoon: 'Xayrli kun',
    goodEvening: 'Xayrli kech',
    tasksScheduled: 'Bugun uchun rejalashtirilgan vazifalar soni:',
    noTasks: 'Vazifalar topilmadi',
    noTasksDesc: 'Sizning jadvalingiz bo\'sh. Dam oling yoki yangi rejalar tuzing!',
    noTasksToday: 'Bugun uchun vazifalar yo\'q',
    noTasksTodayDesc: 'Bugungi kun uchun hech qanday vazifa belgilanmagan. Yangi vazifa qo\'shish tugmasini bosing.',
    createTask: 'Vazifa yaratish',
    newTask: 'Yangi vazifa',
    editTask: 'Vazifani tahrirlash',
    whatToDo: 'Nima qilish kerak?',
    placeholderTask: 'Masalan: Hisobot tayyorlash',
    date: 'Sana',
    time: 'Vaqt',
    description: 'Izoh',
    subtasks: 'Quyi vazifalar',
    addSubtask: 'Quyi vazifa qo\'shish...',
    pinTask: 'Yuqoriga qadash',
    pinnedToTop: 'Yuqoriga qadaldi',
    cancel: 'Bekor qilish',
    save: 'Saqlash',
    create: 'Yaratish',
    settingsTitle: 'Sozlamalar',
    appearance: 'Ko\'rinish',
    darkMode: 'Tungi rejim',
    lightMode: 'Kunduzgi rejim',
    language: 'Til',
    textSize: 'Matn hajmi',
    sound: 'Bildirishnoma ovozi',
    customSound: 'Maxsus ovoz',
    defaultSound: 'Standart ovoz',
    uploadSound: 'Ovoz yuklash',
    reset: 'Qaytarish',
    about: 'Dastur haqida',
    contactAdmin: 'Admin bilan bog\'lanish',
    developer: 'Dasturchi',
    deleteConfirm: 'Ushbu vazifani o\'chirmoqchimisiz?',
    visit: 'Kirish',
    soundLimit: 'Fayl hajmi 4.5MB dan oshmasligi kerak.',
    storageFull: 'Xotira to\'ldi. Kichikroq fayl tanlang.',
    keepOpen: 'Eslatma ishlashi uchun sahifani yopmang!',
  },
  en: {
    all: 'All Tasks',
    today: 'Today',
    upcoming: 'Upcoming',
    pinned: 'Important',
    completed: 'Completed',
    settings: 'Settings',
    search: 'Search tasks...',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    tasksScheduled: 'You have tasks scheduled for today:',
    noTasks: 'No tasks found',
    noTasksDesc: 'Your schedule is clear. Enjoy your free time or plan something new!',
    noTasksToday: 'No tasks for today',
    noTasksTodayDesc: 'You have nothing scheduled for today. Click the button to add a new task.',
    createTask: 'Create Task',
    newTask: 'New Task',
    editTask: 'Edit Task',
    whatToDo: 'What needs to be done?',
    placeholderTask: 'e.g., Plan monthly budget',
    date: 'Date',
    time: 'Time',
    description: 'Description',
    subtasks: 'Subtasks',
    addSubtask: 'Add a subtask...',
    pinTask: 'Pin Task',
    pinnedToTop: 'Pinned to top',
    cancel: 'Cancel',
    save: 'Save Changes',
    create: 'Create Task',
    settingsTitle: 'Settings',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    textSize: 'Text Size',
    sound: 'Notification Sound',
    customSound: 'Custom Sound',
    defaultSound: 'Default Sound',
    uploadSound: 'Upload Sound',
    reset: 'Reset',
    about: 'About',
    contactAdmin: 'Contact Admin',
    developer: 'Developer',
    deleteConfirm: 'Are you sure you want to delete this task?',
    visit: 'Visit',
    soundLimit: 'File size must be under 4.5MB.',
    storageFull: 'Storage full. Please choose a smaller file.',
    keepOpen: 'Keep this tab open for notifications to work!',
  }
};
